verbose: false
instrumentation:
  root: .
  extensions:
    - .js
  default-excludes: true
  excludes:
    - src/**/*.spec.js
    - node_modules
  include-all-sources: true
  es-modules: true
reporting:
  print: summary
  reports:
    - text
    - html
    - json
  dir: ./coverage
  watermarks:
    statements: [50, 80]
    lines: [50, 80]
    functions: [50, 80]
    branches: [50, 80]
  report-config:
    clover: {file: clover.xml}
    cobertura: {file: cobertura-coverage.xml}
    json: {file: coverage.json}
    json-summary: {file: coverage-summary.json}
    lcovonly: {file: lcov.info}
    teamcity: {file: null, blockName: Code Coverage Summary}
    text: {file: null, maxCols: 0}
    text-lcov: {file: lcov.info}
    text-summary: {file: null}
check:
  global:
    statements: 50
    lines: 50
    branches: 50
    functions: 50
    excludes: []
  each:
    statements: 50
    lines: 50
    branches: 50
    functions: 50
    excludes: []
